[versions]
agp = "8.7.3"
kotlin = "2.0.21"
androidxTest = "1.6.1"
androidxTestRunner = "1.6.2"
androidxJunit = "1.2.1"

[libraries]
androidx-test-core = { module = "androidx.test:core-ktx", version.ref = "androidxTest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxJunit" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
